### ISSUE TITLE
lift · liftIO ≠ liftIO

### ISSUE THREAD

**Issue by Shimuuar** [scotty-web/scotty#171]
MonadIO instance catches exceptions raised by IO actions and raises them to ExceptT

```
instance (MonadIO m, ScottyError e) => MonadIO (ActionT e m) where
    liftIO io = ActionT $ do
                    r <- liftIO $ liftM Right io `E.catch` (\ e -> return $ Left $ stringError $ show (e :: E.SomeException))
                    either throwError return r
```

but MonadTrans does no such thing (and I think cannot)

```
instance MonadTrans (ActionT e) where
    lift = ActionT . lift . lift . lift
```

This means that any exceptions raised by code which use lift will not be caught. It also looks like exceptions are not catched elsewhere so they will crash program (I guess). This could for example happen with base monad `ReaderT (Pool Connection) IO` when connection to DB is broken for any reason.

**Comment by chessai** [comment]
Hi @Shimuuar. You're right, I think that the MonadTrans instance can do nothing about this. I think the best we can do is document this difference in behaviour.

**Comment by chessai** [comment]
Acutally, this isn't even true anymore. ActionT's MonadIO instance is now derived and does not catch exceptions by default. I would suggest using liftAndCatchIO. this shouldn't be a problem since you should always have a MonadIO constraint available in such contexts where it is relevant (places relevant in scotty: 99.999% of the time)
