### ISSUE TITLE
Silence "consuming body" or add a switch to toggle debug message

### ISSUE THREAD

**Issue by adamflott** [scotty-web/scotty#174]
We run scotty within Mesos, as a result we don't get much control over stdout handling. Thus, with our high traffic server we get a lot of debug (I presume) messages when we weren't expecting them. The commit in question is: https://github.com/scotty-web/scotty/commit/4997abb62aff05c735f5e7322b03e19ad15f2b38#diff-eb10444a9f8711689d8b5a5841b01da0R142

This might be better for Network.Wai.Middleware.RequestLogger.

**Comment by RyanGlScott** [comment]
I agree that `scotty` probably shouldn't be printing out messages in such a cavalier way. Unfortunately, the `verbose` field of `Options` isn't propagated to the routing functions at the moment, which makes this tricky to fix. I could either:

1. Remove the `putStrLn` statement altogether
2. Change the `scotty` API to be more amenable to debug statements

I'm leaning more towards 1. @edofic, since you implemented the change which added this, is having the `putStrLn` statement important to you?

**Comment by xich** [comment]
I would just remove the `putStrLn`. I suspect it's left over from debugging.

**Comment by adamflott** [comment]
Removing the print works for me

**Comment by RyanGlScott** [comment]
In that case, I'll just charge ahead with that change. I've released it as `scotty-0.10.2` on Hackage.

**Comment by edofic** [comment]
@RyanGIScott I think we're better off without the print
